configured_endpoints: 33
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/citibank-demo-business-inc-diplomat-bit%2Fjocall3-281f0116aaebe7ff8dd6f6bda1b9f7046a9976749a45f11e2b61e5be4d8e0549.yml
openapi_spec_hash: e74063c0e5fa3c56d2acd7f0924cb455
config_hash: eb139e55ae6ecd14d230de79f8530df3
