configured_endpoints: 135
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/citibank-demo-business-inc-diplomat-bit%2Fjocall3-be8af4d61db1e29d1cfcca9dac492f7b88d647d07deb68e10c0c6524b9f290c0.yml
openapi_spec_hash: 732e2a4e753878c3e21a46720ace7dc2
config_hash: 217736d01ce8bcabdc8f4a96fb687acb
