// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package githubcomjocall3go

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"

	"github.com/diplomat-bit/jocall3-go/internal/apijson"
	"github.com/diplomat-bit/jocall3-go/internal/apiquery"
	"github.com/diplomat-bit/jocall3-go/internal/param"
	"github.com/diplomat-bit/jocall3-go/internal/requestconfig"
	"github.com/diplomat-bit/jocall3-go/option"
)

// AIAdService contains methods and other services that help with interacting with
// the jocall3 API.
//
// Note, unlike clients, this service does not read variables from the environment
// automatically. You should not instantiate this service directly, and instead use
// the [NewAIAdService] method instead.
type AIAdService struct {
	Options []option.RequestOption
}

// NewAIAdService generates a new service that applies the given options to each
// request. These options are applied after the parent client's options (if there
// is one), and before any request-specific options.
func NewAIAdService(opts ...option.RequestOption) (r *AIAdService) {
	r = &AIAdService{}
	r.Options = opts
	return
}

// Retrieves a list of all video advertisements previously generated by the user in
// the AI Ad Studio.
func (r *AIAdService) List(ctx context.Context, query AIAdListParams, opts ...option.RequestOption) (res *AIAdListResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "ai/ads"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, &res, opts...)
	return
}

// Submits a request to generate a high-quality video ad using the advanced Veo 2.0
// generative AI model. This is an asynchronous operation, suitable for standard ad
// content creation.
func (r *AIAdService) Generate(ctx context.Context, body AIAdGenerateParams, opts ...option.RequestOption) (res *AIAdGenerateResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "ai/ads/generate"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return
}

// Polls the real-time status of an asynchronous video generation operation. Once
// complete ('done'), the response includes a temporary, signed URL to access and
// download the generated video asset.
func (r *AIAdService) GetOperation(ctx context.Context, operationID string, opts ...option.RequestOption) (res *AIAdGetOperationResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	if operationID == "" {
		err = errors.New("missing required operationId parameter")
		return
	}
	path := fmt.Sprintf("ai/ads/operations/%s", operationID)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return
}

type AIAdListResponse = interface{}

type AIAdGenerateResponse = interface{}

type AIAdGetOperationResponse = interface{}

type AIAdListParams struct {
	// Maximum number of items to return in a single page.
	Limit param.Field[int64] `query:"limit"`
	// Number of items to skip before starting to collect the result set.
	Offset param.Field[int64] `query:"offset"`
	// Filter ads by their generation status.
	Status param.Field[string] `query:"status"`
}

// URLQuery serializes [AIAdListParams]'s query parameters as `url.Values`.
func (r AIAdListParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatComma,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type AIAdGenerateParams struct {
}

func (r AIAdGenerateParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}
