// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package githubcomjocall3go

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"slices"

	"github.com/diplomat-bit/jocall3-go/internal/apijson"
	"github.com/diplomat-bit/jocall3-go/internal/requestconfig"
	"github.com/diplomat-bit/jocall3-go/option"
)

// CorporateComplianceAuditService contains methods and other services that help
// with interacting with the jocall3 API.
//
// Note, unlike clients, this service does not read variables from the environment
// automatically. You should not instantiate this service directly, and instead use
// the [NewCorporateComplianceAuditService] method instead.
type CorporateComplianceAuditService struct {
	Options []option.RequestOption
}

// NewCorporateComplianceAuditService generates a new service that applies the
// given options to each request. These options are applied after the parent
// client's options (if there is one), and before any request-specific options.
func NewCorporateComplianceAuditService(opts ...option.RequestOption) (r *CorporateComplianceAuditService) {
	r = &CorporateComplianceAuditService{}
	r.Options = opts
	return
}

// Initiates an AI-powered compliance audit for a specific period or scope,
// generating a comprehensive report detailing adherence to regulatory frameworks,
// internal policies, and flagging potential risks.
func (r *CorporateComplianceAuditService) Request(ctx context.Context, body CorporateComplianceAuditRequestParams, opts ...option.RequestOption) (res *CorporateComplianceAuditRequestResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "corporate/compliance/audits"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return
}

// Retrieves the full report generated by an AI-driven compliance audit.
func (r *CorporateComplianceAuditService) GetReport(ctx context.Context, auditID string, opts ...option.RequestOption) (res *CorporateComplianceAuditGetReportResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	if auditID == "" {
		err = errors.New("missing required auditId parameter")
		return
	}
	path := fmt.Sprintf("corporate/compliance/audits/%s/report", auditID)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return
}

type CorporateComplianceAuditRequestResponse = interface{}

type CorporateComplianceAuditGetReportResponse struct {
	// The period covered by this audit report.
	PeriodCovered interface{}                                   `json:"periodCovered,required"`
	JSON          corporateComplianceAuditGetReportResponseJSON `json:"-"`
}

// corporateComplianceAuditGetReportResponseJSON contains the JSON metadata for the
// struct [CorporateComplianceAuditGetReportResponse]
type corporateComplianceAuditGetReportResponseJSON struct {
	PeriodCovered apijson.Field
	raw           string
	ExtraFields   map[string]apijson.Field
}

func (r *CorporateComplianceAuditGetReportResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r corporateComplianceAuditGetReportResponseJSON) RawJSON() string {
	return r.raw
}

type CorporateComplianceAuditRequestParams struct {
}

func (r CorporateComplianceAuditRequestParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}
